In [3]:
pip install pandas

<class 'OSError'>: Not available

In [4]:
import pandas as pd

print(pd.__version__)

3.0.2

In [5]:
import pandas as pd
marks = pd.Series([80,90,75,65])
print(marks)

0    80
1    90
2    75
3    65
dtype: int64

In [6]:
fruits = pd.Series(["Apple","Mango","Banana"])
print(fruits)

0     Apple
1     Mango
2    Banana
dtype: str

In [7]:
#Access Values
print(fruits[0])

Apple

In [8]:
#Custom Index
marks = pd.Series([80,90,75],index=["A","B","C"])
print(marks)

A    80
B    90
C    75
dtype: int64

In [11]:
#Create DataFrame
import pandas as pd
student={
"Roll":[101,102,103],
"Name":["Aman","Riya","John"],
"Marks":[90,95,76]
}
df=pd.DataFrame(student)
print(df)

   Roll  Name  Marks
0   101  Aman     90
1   102  Riya     95
2   103  John     76

In [12]:
#View Data
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.index)
print(df.info())
print(df.describe())

   Roll  Name  Marks
0   101  Aman     90
1   102  Riya     95
2   103  John     76
   Roll  Name  Marks
0   101  Aman     90
1   102  Riya     95
2   103  John     76
(3, 3)
Index(['Roll', 'Name', 'Marks'], dtype='str')
RangeIndex(start=0, stop=3, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Roll    3 non-null      int64
 1   Name    3 non-null      str
 2   Marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 132.0 bytes
None
        Roll      Marks
count    3.0   3.000000
mean   102.0  87.000000
std      1.0   9.848858
min    101.0  76.000000
25%    101.5  83.000000
50%    102.0  90.000000
75%    102.5  92.500000
max    103.0  95.000000

In [13]:
#Column Selection
print(df["Name"])
#Multiple Columns
print(df[["Name","Marks"]])

0    Aman
1    Riya
2    John
Name: Name, dtype: str
   Name  Marks
0  Aman     90
1  Riya     95
2  John     76

In [14]:
#Selecting Rows
print(df.loc[0])
print(df.iloc[1])
#Specific Value
print(df.loc[2,"Marks"])

Roll      101
Name     Aman
Marks      90
Name: 0, dtype: object
Roll      102
Name     Riya
Marks      95
Name: 1, dtype: object
76

In [12]:
import pandas as  pd 
f=pd.read_csv("Book1.csv")
print(f)

    Student  English  Math  Science  Social Studies  Computer
0     Alice       85    92       88              81        95
1       Bob       78    84       80              76        89
2   Charlie       91    87       93              90        94
3     David       69    75       72              70        78
4      Emma       88    90       86              85        91
5     Frank       74    79       77              73        82
6     Grace       95    98       96              94        99
7     Henry       82    85       84              80        87
8  Isabella       89    91       90              88        93
9      Jack       76    81       79              75        84

In [16]:
import pandas as pd

df = pd.read_csv("Book1.csv")

# Display only Name and Marks
result = df[["Student", "Math"]]

print(result)

    Student  Math
0     Alice    92
1       Bob    84
2   Charlie    87
3     David    75
4      Emma    90
5     Frank    79
6     Grace    98
7     Henry    85
8  Isabella    91
9      Jack    81

In [18]:
#Fill Missing
df.fillna("Unknown")

    Student  English  Math  Science  Social Studies  Computer
0     Alice       85    92       88              81        95
1       Bob       78    84       80              76        89
2   Charlie       91    87       93              90        94
3     David       69    75       72              70        78
4      Emma       88    90       86              85        91
5     Frank       74    79       77              73        82
6     Grace       95    98       96              94        99
7     Henry       82    85       84              80        87
8  Isabella       89    91       90              88        93
9      Jack       76    81       79              75        84

In [19]:
#Check Missing Values
print(df.isnull())

   Student  English   Math  Science  Social Studies  Computer
0    False    False  False    False           False     False
1    False    False  False    False           False     False
2    False    False  False    False           False     False
3    False    False  False    False           False     False
4    False    False  False    False           False     False
5    False    False  False    False           False     False
6    False    False  False    False           False     False
7    False    False  False    False           False     False
8    False    False  False    False           False     False
9    False    False  False    False           False     False

In [17]:
#Count Missing
print(df.isnull().sum())

Student           0
English           0
Math              0
Science           0
Social Studies    0
Computer          0
dtype: int64

In [18]:
#Marks greater than 80
df[df["Marks"]>80]

#Multiple Conditions
df[(df["Marks"]>80) & (df["Roll"]>18)]

   Roll  Name  Marks
0   101  Aman     90
1   102  Riya     95

In [19]:
#Ascending
df.sort_values("Marks")
#Descending
df.sort_values("Marks",ascending=False)

   Roll  Name  Marks
1   102  Riya     95
0   101  Aman     90
2   103  John     76

In [6]:
import pandas as  pd 
df=pd.read_csv("employee.csv")
print(df)

     id     name department   salary
0   101    Alice         HR  50000.0
1   102      Bob         IT  65000.0
2   103  Charlie    Finance  70000.0
3   104    David  Marketing      NaN
4   105      Eva      Sales  55000.0
5   106    Frank         IT  60000.0
6   107    Grace         HR      0.0
7   108    Helen    Finance  72000.0
8   109      Ian  Marketing  68000.0
9   110     Jack      Sales  53000.0
10  111    Karen         IT  75000.0
11  112      Leo         HR  58000.0
12  113     Mona    Finance      NaN
13  114     Nina  Marketing  62000.0
14  115    Oscar      Sales  71000.0
15  116     Paul         IT  66000.0
16  117    Queen         HR  54000.0
17  118     Ryan    Finance  69000.0
18  119   Sophia  Marketing  73000.0
19  120      Tom      Sales  64000.0

In [7]:
df["Bonus"]=5000
df["Total"]=df["salary"]+df["Bonus"]
print(df)

     id     name department   salary  Bonus    Total
0   101    Alice         HR  50000.0   5000  55000.0
1   102      Bob         IT  65000.0   5000  70000.0
2   103  Charlie    Finance  70000.0   5000  75000.0
3   104    David  Marketing      NaN   5000      NaN
4   105      Eva      Sales  55000.0   5000  60000.0
5   106    Frank         IT  60000.0   5000  65000.0
6   107    Grace         HR      0.0   5000   5000.0
7   108    Helen    Finance  72000.0   5000  77000.0
8   109      Ian  Marketing  68000.0   5000  73000.0
9   110     Jack      Sales  53000.0   5000  58000.0
10  111    Karen         IT  75000.0   5000  80000.0
11  112      Leo         HR  58000.0   5000  63000.0
12  113     Mona    Finance      NaN   5000      NaN
13  114     Nina  Marketing  62000.0   5000  67000.0
14  115    Oscar      Sales  71000.0   5000  76000.0
15  116     Paul         IT  66000.0   5000  71000.0
16  117    Queen         HR  54000.0   5000  59000.0
17  118     Ryan    Finance  69000.0   5000  74000.0
18  119   Sophia  Marketing  73000.0   5000  78000.0
19  120      Tom      Sales  64000.0   5000  69000.0

In [8]:
#Average Salary
df.groupby("department")["salary"].mean()

department
Finance      70333.333333
HR           40500.000000
IT           66500.000000
Marketing    67666.666667
Sales        60750.000000
Name: salary, dtype: float64

In [29]:
#Sum
df.groupby("department")["salary"].sum()

department
Finance      211000.0
HR           162000.0
IT           266000.0
Marketing    203000.0
Sales        243000.0
Name: salary, dtype: float64

In [30]:
#Maximum
df.groupby("department")["salary"].max()

department
Finance      72000.0
HR           58000.0
IT           75000.0
Marketing    73000.0
Sales        71000.0
Name: salary, dtype: float64

In [31]:
#Count
df.groupby("department")["salary"].count()

department
Finance      3
HR           4
IT           4
Marketing    3
Sales        4
Name: salary, dtype: int64

In [9]:
df1 = pd.DataFrame({'id': [101, 102, 103], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [101, 102, 103], 'department': ['HR', 'IT', 'Finance']})
print(df1)
print(df2)
result = pd.merge(df1,df2, on="id")
print(result)

    id     name
0  101    Alice
1  102      Bob
2  103  Charlie
    id department
0  101         HR
1  102         IT
2  103    Finance
    id     name department
0  101    Alice         HR
1  102      Bob         IT
2  103  Charlie    Finance